/** ISO 3166-1 alpha-2 国家/地区代码 → 中英文名（静态对照，不依赖运行时 ICU） */
export const COUNTRY_NAMES: Record<string, { zh: string; en: string }> = {
  AD: { zh: "安道尔", en: "Andorra" },
  AE: { zh: "阿联酋", en: "United Arab Emirates" },
  AF: { zh: "阿富汗", en: "Afghanistan" },
  AG: { zh: "安提瓜和巴布达", en: "Antigua and Barbuda" },
  AI: { zh: "安圭拉", en: "Anguilla" },
  AL: { zh: "阿尔巴尼亚", en: "Albania" },
  AM: { zh: "亚美尼亚", en: "Armenia" },
  AO: { zh: "安哥拉", en: "Angola" },
  AQ: { zh: "南极洲", en: "Antarctica" },
  AR: { zh: "阿根廷", en: "Argentina" },
  AS: { zh: "美属萨摩亚", en: "American Samoa" },
  AT: { zh: "奥地利", en: "Austria" },
  AU: { zh: "澳大利亚", en: "Australia" },
  AW: { zh: "阿鲁巴", en: "Aruba" },
  AX: { zh: "奥兰群岛", en: "Åland Islands" },
  AZ: { zh: "阿塞拜疆", en: "Azerbaijan" },
  BA: { zh: "波黑", en: "Bosnia and Herzegovina" },
  BB: { zh: "巴巴多斯", en: "Barbados" },
  BD: { zh: "孟加拉国", en: "Bangladesh" },
  BE: { zh: "比利时", en: "Belgium" },
  BF: { zh: "布基纳法索", en: "Burkina Faso" },
  BG: { zh: "保加利亚", en: "Bulgaria" },
  BH: { zh: "巴林", en: "Bahrain" },
  BI: { zh: "布隆迪", en: "Burundi" },
  BJ: { zh: "贝宁", en: "Benin" },
  BL: { zh: "圣巴泰勒米", en: "Saint Barthélemy" },
  BM: { zh: "百慕大", en: "Bermuda" },
  BN: { zh: "文莱", en: "Brunei" },
  BO: { zh: "玻利维亚", en: "Bolivia" },
  BQ: { zh: "荷兰加勒比区", en: "Caribbean Netherlands" },
  BR: { zh: "巴西", en: "Brazil" },
  BS: { zh: "巴哈马", en: "Bahamas" },
  BT: { zh: "不丹", en: "Bhutan" },
  BV: { zh: "布韦岛", en: "Bouvet Island" },
  BW: { zh: "博茨瓦纳", en: "Botswana" },
  BY: { zh: "白俄罗斯", en: "Belarus" },
  BZ: { zh: "伯利兹", en: "Belize" },
  CA: { zh: "加拿大", en: "Canada" },
  CC: { zh: "科科斯群岛", en: "Cocos Islands" },
  CD: { zh: "刚果（金）", en: "DR Congo" },
  CF: { zh: "中非", en: "Central African Republic" },
  CG: { zh: "刚果（布）", en: "Republic of the Congo" },
  CH: { zh: "瑞士", en: "Switzerland" },
  CI: { zh: "科特迪瓦", en: "Côte d'Ivoire" },
  CK: { zh: "库克群岛", en: "Cook Islands" },
  CL: { zh: "智利", en: "Chile" },
  CM: { zh: "喀麦隆", en: "Cameroon" },
  CN: { zh: "中国", en: "China" },
  CO: { zh: "哥伦比亚", en: "Colombia" },
  CR: { zh: "哥斯达黎加", en: "Costa Rica" },
  CU: { zh: "古巴", en: "Cuba" },
  CV: { zh: "佛得角", en: "Cape Verde" },
  CW: { zh: "库拉索", en: "Curaçao" },
  CX: { zh: "圣诞岛", en: "Christmas Island" },
  CY: { zh: "塞浦路斯", en: "Cyprus" },
  CZ: { zh: "捷克", en: "Czechia" },
  DE: { zh: "德国", en: "Germany" },
  DJ: { zh: "吉布提", en: "Djibouti" },
  DK: { zh: "丹麦", en: "Denmark" },
  DM: { zh: "多米尼克", en: "Dominica" },
  DO: { zh: "多米尼加", en: "Dominican Republic" },
  DZ: { zh: "阿尔及利亚", en: "Algeria" },
  EC: { zh: "厄瓜多尔", en: "Ecuador" },
  EE: { zh: "爱沙尼亚", en: "Estonia" },
  EG: { zh: "埃及", en: "Egypt" },
  EH: { zh: "西撒哈拉", en: "Western Sahara" },
  ER: { zh: "厄立特里亚", en: "Eritrea" },
  ES: { zh: "西班牙", en: "Spain" },
  ET: { zh: "埃塞俄比亚", en: "Ethiopia" },
  FI: { zh: "芬兰", en: "Finland" },
  FJ: { zh: "斐济", en: "Fiji" },
  FK: { zh: "福克兰群岛", en: "Falkland Islands" },
  FM: { zh: "密克罗尼西亚", en: "Micronesia" },
  FO: { zh: "法罗群岛", en: "Faroe Islands" },
  FR: { zh: "法国", en: "France" },
  GA: { zh: "加蓬", en: "Gabon" },
  GB: { zh: "英国", en: "United Kingdom" },
  GD: { zh: "格林纳达", en: "Grenada" },
  GE: { zh: "格鲁吉亚", en: "Georgia" },
  GF: { zh: "法属圭亚那", en: "French Guiana" },
  GG: { zh: "根西岛", en: "Guernsey" },
  GH: { zh: "加纳", en: "Ghana" },
  GI: { zh: "直布罗陀", en: "Gibraltar" },
  GL: { zh: "格陵兰", en: "Greenland" },
  GM: { zh: "冈比亚", en: "Gambia" },
  GN: { zh: "几内亚", en: "Guinea" },
  GP: { zh: "瓜德罗普", en: "Guadeloupe" },
  GQ: { zh: "赤道几内亚", en: "Equatorial Guinea" },
  GR: { zh: "希腊", en: "Greece" },
  GS: { zh: "南乔治亚和南桑威奇群岛", en: "South Georgia" },
  GT: { zh: "危地马拉", en: "Guatemala" },
  GU: { zh: "关岛", en: "Guam" },
  GW: { zh: "几内亚比绍", en: "Guinea-Bissau" },
  GY: { zh: "圭亚那", en: "Guyana" },
  HK: { zh: "中国香港", en: "Hong Kong" },
  HM: { zh: "赫德岛和麦克唐纳群岛", en: "Heard Island" },
  HN: { zh: "洪都拉斯", en: "Honduras" },
  HR: { zh: "克罗地亚", en: "Croatia" },
  HT: { zh: "海地", en: "Haiti" },
  HU: { zh: "匈牙利", en: "Hungary" },
  ID: { zh: "印度尼西亚", en: "Indonesia" },
  IE: { zh: "爱尔兰", en: "Ireland" },
  IL: { zh: "以色列", en: "Israel" },
  IM: { zh: "马恩岛", en: "Isle of Man" },
  IN: { zh: "印度", en: "India" },
  IO: { zh: "英属印度洋领地", en: "British Indian Ocean Territory" },
  IQ: { zh: "伊拉克", en: "Iraq" },
  IR: { zh: "伊朗", en: "Iran" },
  IS: { zh: "冰岛", en: "Iceland" },
  IT: { zh: "意大利", en: "Italy" },
  JE: { zh: "泽西岛", en: "Jersey" },
  JM: { zh: "牙买加", en: "Jamaica" },
  JO: { zh: "约旦", en: "Jordan" },
  JP: { zh: "日本", en: "Japan" },
  KE: { zh: "肯尼亚", en: "Kenya" },
  KG: { zh: "吉尔吉斯斯坦", en: "Kyrgyzstan" },
  KH: { zh: "柬埔寨", en: "Cambodia" },
  KI: { zh: "基里巴斯", en: "Kiribati" },
  KM: { zh: "科摩罗", en: "Comoros" },
  KN: { zh: "圣基茨和尼维斯", en: "Saint Kitts and Nevis" },
  KP: { zh: "朝鲜", en: "North Korea" },
  KR: { zh: "韩国", en: "South Korea" },
  KW: { zh: "科威特", en: "Kuwait" },
  KY: { zh: "开曼群岛", en: "Cayman Islands" },
  KZ: { zh: "哈萨克斯坦", en: "Kazakhstan" },
  LA: { zh: "老挝", en: "Laos" },
  LB: { zh: "黎巴嫩", en: "Lebanon" },
  LC: { zh: "圣卢西亚", en: "Saint Lucia" },
  LI: { zh: "列支敦士登", en: "Liechtenstein" },
  LK: { zh: "斯里兰卡", en: "Sri Lanka" },
  LR: { zh: "利比里亚", en: "Liberia" },
  LS: { zh: "莱索托", en: "Lesotho" },
  LT: { zh: "立陶宛", en: "Lithuania" },
  LU: { zh: "卢森堡", en: "Luxembourg" },
  LV: { zh: "拉脱维亚", en: "Latvia" },
  LY: { zh: "利比亚", en: "Libya" },
  MA: { zh: "摩洛哥", en: "Morocco" },
  MC: { zh: "摩纳哥", en: "Monaco" },
  MD: { zh: "摩尔多瓦", en: "Moldova" },
  ME: { zh: "黑山", en: "Montenegro" },
  MF: { zh: "法属圣马丁", en: "Saint Martin" },
  MG: { zh: "马达加斯加", en: "Madagascar" },
  MH: { zh: "马绍尔群岛", en: "Marshall Islands" },
  MK: { zh: "北马其顿", en: "North Macedonia" },
  ML: { zh: "马里", en: "Mali" },
  MM: { zh: "缅甸", en: "Myanmar" },
  MN: { zh: "蒙古", en: "Mongolia" },
  MO: { zh: "中国澳门", en: "Macau" },
  MP: { zh: "北马里亚纳群岛", en: "Northern Mariana Islands" },
  MQ: { zh: "马提尼克", en: "Martinique" },
  MR: { zh: "毛里塔尼亚", en: "Mauritania" },
  MS: { zh: "蒙特塞拉特", en: "Montserrat" },
  MT: { zh: "马耳他", en: "Malta" },
  MU: { zh: "毛里求斯", en: "Mauritius" },
  MV: { zh: "马尔代夫", en: "Maldives" },
  MW: { zh: "马拉维", en: "Malawi" },
  MX: { zh: "墨西哥", en: "Mexico" },
  MY: { zh: "马来西亚", en: "Malaysia" },
  MZ: { zh: "莫桑比克", en: "Mozambique" },
  NA: { zh: "纳米比亚", en: "Namibia" },
  NC: { zh: "新喀里多尼亚", en: "New Caledonia" },
  NE: { zh: "尼日尔", en: "Niger" },
  NF: { zh: "诺福克岛", en: "Norfolk Island" },
  NG: { zh: "尼日利亚", en: "Nigeria" },
  NI: { zh: "尼加拉瓜", en: "Nicaragua" },
  NL: { zh: "荷兰", en: "Netherlands" },
  NO: { zh: "挪威", en: "Norway" },
  NP: { zh: "尼泊尔", en: "Nepal" },
  NR: { zh: "瑙鲁", en: "Nauru" },
  NU: { zh: "纽埃", en: "Niue" },
  NZ: { zh: "新西兰", en: "New Zealand" },
  OM: { zh: "阿曼", en: "Oman" },
  PA: { zh: "巴拿马", en: "Panama" },
  PE: { zh: "秘鲁", en: "Peru" },
  PF: { zh: "法属波利尼西亚", en: "French Polynesia" },
  PG: { zh: "巴布亚新几内亚", en: "Papua New Guinea" },
  PH: { zh: "菲律宾", en: "Philippines" },
  PK: { zh: "巴基斯坦", en: "Pakistan" },
  PL: { zh: "波兰", en: "Poland" },
  PM: { zh: "圣皮埃尔和密克隆", en: "Saint Pierre and Miquelon" },
  PN: { zh: "皮特凯恩群岛", en: "Pitcairn Islands" },
  PR: { zh: "波多黎各", en: "Puerto Rico" },
  PS: { zh: "巴勒斯坦", en: "Palestine" },
  PT: { zh: "葡萄牙", en: "Portugal" },
  PW: { zh: "帕劳", en: "Palau" },
  PY: { zh: "巴拉圭", en: "Paraguay" },
  QA: { zh: "卡塔尔", en: "Qatar" },
  RE: { zh: "留尼汪", en: "Réunion" },
  RO: { zh: "罗马尼亚", en: "Romania" },
  RS: { zh: "塞尔维亚", en: "Serbia" },
  RU: { zh: "俄罗斯", en: "Russia" },
  RW: { zh: "卢旺达", en: "Rwanda" },
  SA: { zh: "沙特阿拉伯", en: "Saudi Arabia" },
  SB: { zh: "所罗门群岛", en: "Solomon Islands" },
  SC: { zh: "塞舌尔", en: "Seychelles" },
  SD: { zh: "苏丹", en: "Sudan" },
  SE: { zh: "瑞典", en: "Sweden" },
  SG: { zh: "新加坡", en: "Singapore" },
  SH: { zh: "圣赫勒拿", en: "Saint Helena" },
  SI: { zh: "斯洛文尼亚", en: "Slovenia" },
  SJ: { zh: "斯瓦尔巴和扬马延", en: "Svalbard and Jan Mayen" },
  SK: { zh: "斯洛伐克", en: "Slovakia" },
  SL: { zh: "塞拉利昂", en: "Sierra Leone" },
  SM: { zh: "圣马力诺", en: "San Marino" },
  SN: { zh: "塞内加尔", en: "Senegal" },
  SO: { zh: "索马里", en: "Somalia" },
  SR: { zh: "苏里南", en: "Suriname" },
  SS: { zh: "南苏丹", en: "South Sudan" },
  ST: { zh: "圣多美和普林西比", en: "São Tomé and Príncipe" },
  SV: { zh: "萨尔瓦多", en: "El Salvador" },
  SX: { zh: "荷属圣马丁", en: "Sint Maarten" },
  SY: { zh: "叙利亚", en: "Syria" },
  SZ: { zh: "斯威士兰", en: "Eswatini" },
  TC: { zh: "特克斯和凯科斯群岛", en: "Turks and Caicos Islands" },
  TD: { zh: "乍得", en: "Chad" },
  TF: { zh: "法属南部领地", en: "French Southern Territories" },
  TG: { zh: "多哥", en: "Togo" },
  TH: { zh: "泰国", en: "Thailand" },
  TJ: { zh: "塔吉克斯坦", en: "Tajikistan" },
  TK: { zh: "托克劳", en: "Tokelau" },
  TL: { zh: "东帝汶", en: "Timor-Leste" },
  TM: { zh: "土库曼斯坦", en: "Turkmenistan" },
  TN: { zh: "突尼斯", en: "Tunisia" },
  TO: { zh: "汤加", en: "Tonga" },
  TR: { zh: "土耳其", en: "Turkey" },
  TT: { zh: "特立尼达和多巴哥", en: "Trinidad and Tobago" },
  TV: { zh: "图瓦卢", en: "Tuvalu" },
  TW: { zh: "中国台湾", en: "Taiwan" },
  TZ: { zh: "坦桑尼亚", en: "Tanzania" },
  UA: { zh: "乌克兰", en: "Ukraine" },
  UG: { zh: "乌干达", en: "Uganda" },
  UM: { zh: "美国本土外小岛屿", en: "US Outlying Islands" },
  US: { zh: "美国", en: "United States" },
  UY: { zh: "乌拉圭", en: "Uruguay" },
  UZ: { zh: "乌兹别克斯坦", en: "Uzbekistan" },
  VA: { zh: "梵蒂冈", en: "Vatican City" },
  VC: { zh: "圣文森特和格林纳丁斯", en: "Saint Vincent and the Grenadines" },
  VE: { zh: "委内瑞拉", en: "Venezuela" },
  VG: { zh: "英属维尔京群岛", en: "British Virgin Islands" },
  VI: { zh: "美属维尔京群岛", en: "US Virgin Islands" },
  VN: { zh: "越南", en: "Vietnam" },
  VU: { zh: "瓦努阿图", en: "Vanuatu" },
  WF: { zh: "瓦利斯和富图纳", en: "Wallis and Futuna" },
  WS: { zh: "萨摩亚", en: "Samoa" },
  XK: { zh: "科索沃", en: "Kosovo" },
  YE: { zh: "也门", en: "Yemen" },
  YT: { zh: "马约特", en: "Mayotte" },
  ZA: { zh: "南非", en: "South Africa" },
  ZM: { zh: "赞比亚", en: "Zambia" },
  ZW: { zh: "津巴布韦", en: "Zimbabwe" },
};
